name: CI workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get release version description
        id: get_version_desc
        run: echo ::set-output name=VERSION_DESC::${GITHUB_REF/refs\/releases\/}