name: CI workflow

on:
  release:
    types: [published]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get release version description
        id: get_version_desc
        run: echo ${ github.event.release.body }