# https://gist.github.com/sualeh/ae78dc16123899d7942bc38baba5203c
# https://github.com/rnett/compiler-plugin-utils/blob/f2cb49cdc683d24b3c6793fe1cbc6a76af29fc8f/.github/workflows/ci.yml

name: Upload to Bintray workflow

on:
  release:
    types: [ published ]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup JDK1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache .gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode
        run: |
          echo "${{secrets.OSSRH_GPG_SECRET_KEY}}" > ~/.gradle/secring.gpg.b64
          cd ~/.gradle
          ls -a
          base64 -d ~/.gradle/secring.gpg.b64 > ~/.gradle/secring.gpg

      - name: Get release version
        id: get_version
        run: echo ::set-output name=VERSION_NAME::${GITHUB_REF/refs\/tags\//}

      - name: Publish to central repository
        env:
          ORG_GRADLE_PROJECT_mavenCentralRepositoryPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralRepositoryUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.OSSRH_GPG_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.OSSRH_GPG_KEY_PASSWORD }}
          OSSRH_USERNAME: ${{secrets.SONATYPE_USERNAME}}
          OSSRH_PASSWORD: ${{secrets.SONATYPE_PASSWORD}}
          GRADLE_OPTS: -Xmx2048m -XX:MaxPermSize=512m
        run: ./gradlew publish --no-daemon --no-parallel --stacktrace
