# https://gist.github.com/sualeh/ae78dc16123899d7942bc38baba5203c
# https://github.com/rnett/compiler-plugin-utils/blob/f2cb49cdc683d24b3c6793fe1cbc6a76af29fc8f/.github/workflows/ci.yml

name: Upload to Bintray workflow

on:
  release:
    types: [ published ]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant permission
        run: chmod +x gradlew

      - name: Get release version
        id: get_version
        run: echo ::set-output name=VERSION_NAME::${GITHUB_REF/refs\/tags\//}

      - name: Publish to central repository
        env:
          ORG_GRADLE_PROJECT_mavenCentralRepositoryPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralRepositoryUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.OSSRH_GPG_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryPassword: ${{ secrets.OSSRH_GPG_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          GRADLE_OPTS: -Xmx2048m -XX:MaxPermSize=512m
        run: ./gradlew publish --no-daemon --no-parallel --stacktrace
