name: Upload to Bintray

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Grant permission
      run: chmod +x gradlew

    - name: Release tag
        id: release_tag
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
        
    - name: Upload library
      env:
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
        LIBRARY_VERSION: ${{ steps.release_tag.outputs.SOURCE_TAG }}
      run: ./gradlew clean install bintrayUpload --stacktrace
