name: Upload to Bintray

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - run: echo Setup done!
        
    - name: Upload library
      env:
        bintrayUser: ${{ secrets.BINTRAY_USER }}
        bintrayApiKey: ${{ secrets.BINTRAY_API_KEY }}
      run: ./gradlew bintrayUpload --stacktrace
      
    - run: echo Upload done!
